### ISSUE TITLE
Make it so you can close the main window so all your other documents that are open don't close

### ISSUE THREAD

**Issue by CarJem** [Vista1nik/GDocs#2]
I was working on a couple of essays, and sometimes I would be done with one document and close it, and because it was the main window, it would close them all. Not really practical to work like this in this situation.

**Comment by Vista1nik** [comment]
Okay 👍

**Comment by Vista1nik** [comment]
Try a new version 😺 

https://github.com/Vista1nik/GDocs/releases/tag/1.1.0

**Comment by CarJem** [comment]
I can confirm that the problem is not exactly solved in the way I discovered, but it is possible to workaround if I make a new document directly from the document editor closing the window that created the new document, it will close that too.

The new window function does allow multiple instances, however, if windows are created within that instance, they will also close if the initial window is closed.

If this confusing let me know.

**Comment by Vista1nik** [comment]
Fixed in https://github.com/Vista1nik/ThunderDocs/commit/5b58d421c6c92be6f812fa073d83329a3345308e
